project_id = "mswngfckwjatgwkcpoko"

[functions.send-registration-email]
verify_jwt = false

[functions.notify-payment]
verify_jwt = true

[functions.notify-enrollment-approved]
verify_jwt = true

[functions.issue-certificate]
verify_jwt = true

[functions.midtrans-create-transaction]
verify_jwt = true

[functions.midtrans-webhook]
verify_jwt = false

[functions.admin-manage-roles]
verify_jwt = true
